spring:
  aop:
    proxy-target-class: true
  datasource:
    primary:
      jdbcurl: jdbc:mysql://127.0.0.1:3306/demo?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 111111
      driver-class-name: com.mysql.cj.jdbc.Driver
    second:
      jdbcurl: jdbc:mysql://127.0.0.1:3306/demo2?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 111111
      driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 3000
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: select 1

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
debug: true
pagehelper:
  auto-dialect: false
  helper-dialect: mysql
  default-count: countSql